### ISSUE TITLE
JavaScript not linked to HMTL properly

### ISSUE THREAD

**Issue by jeryelblanco** [learn-co-curriculum/phase-1-practice-dog-ceo#10]
### Canvas Link

https://learning.flatironschool.com/courses/6272/assignments/230879?module_item_id=540176

### Concern

Script is not loading because defer is not included in the script tag

**Comment by lizbur10** [comment]
Thanks for raising this issue, @jeryelblanco! Delaying the execution of the js was intended to be part of the requirements for this lab. I have added a hint to make that clear.

Thanks for contributing to the Flatiron School curriculum 💙
